// The normalised name key — the one definition, for the whole repo.
//
// Postgres stores this value in the `name_search` generated column on
// `artists`, `artist_aliases` and `organisations`. Since
// migrations/supabase_migration_normalise_name_key_function.sql all three
// columns are generated by calling a single SQL function:
//
//     public.normalise_name_key(name)
//       -> regexp_replace(lower(public.immutable_unaccent(value)), '[^a-z0-9]', '', 'g')
//
// i.e. strip diacritics, lowercase, then drop everything that isn't a letter
// or a digit. "Ostgut Ton", "ostgut ton" and "Ostgut-Ton" all collapse to
// "ostgutton", and "ØTTA" collapses to "otta".
//
// Anything that compares a user-supplied string against name_search — the
// directory search, the admin organisation filters, the duplicate checks, the
// enrichment scripts — has to produce the identical key, or the comparison
// silently misses. This module is that computation. It is plain .mjs rather
// than .ts precisely so that both sides can share it: the Next app imports it
// from TypeScript, and the scripts run it under bare `node`.
//
// The hard part is unaccent(). It isn't an algorithm, it's contrib/unaccent's
// lookup table, so JavaScript can't derive it. NFD decomposition covers the
// accented letters that are canonically "base + combining mark" (é, ü, ż) —
// but not the ones carrying the mark inside the codepoint. NFD leaves "Ø"
// intact, the [^a-z0-9] strip then deletes it outright, and a search for
// "ØTTA" goes looking for "tta". Ø, æ, œ, ß, ł, đ, ð, þ and friends all fail
// that way, which is most of Scandinavia and Poland.
//
// So the exceptions are not hand-written here. UNACCENT_DELTA is generated by
// scripts/generate-unaccent-delta.mjs, which asks the database what
// unaccent() does to every character in the BMP and keeps the ones where NFD
// would disagree about the final key. src/lib/name-key.test.ts then re-checks
// the assembled function against the same database. Previous attempts at this
// were hand-maintained tables in four places, which is four chances to drift;
// the point of the codegen is that no human writes the table.

import { UNACCENT_DELTA } from "./unaccent-delta.generated.mjs";

// A Map rather than the raw object: lookups can't collide with anything on
// Object.prototype, whatever the input.
const DELTA = new Map(Object.entries(UNACCENT_DELTA));

const COMBINING_MARKS = /[̀-ͯ]/g;

/**
 * Strip diacritics the way Postgres's unaccent() does.
 *
 * Case and punctuation are left alone — this is the romanisation step only.
 * Characters unaccent() can't romanise (Cyrillic, Greek, CJK) pass through
 * unchanged, exactly as they do in Postgres.
 *
 * @param {unknown} value
 * @returns {string}
 */
export function unaccent(value) {
  if (typeof value !== "string") return "";
  let out = "";
  // Iterating the string yields whole code points, so astral characters are
  // never split; they simply miss the table and pass through.
  //
  // A table hit is substituted VERBATIM and deliberately not put through NFD
  // afterwards: the table already holds Postgres's own answer for that
  // character, and re-decomposing it would overrule the authority we just
  // consulted. U+212B (the angstrom sign) is the case that proves it —
  // Postgres leaves it alone, so its key is empty, but NFD decomposes it to
  // "A" + combining ring and would key it as "a".
  for (const ch of value) {
    const mapped = DELTA.get(ch);
    out += mapped !== undefined
      ? mapped
      : ch.normalize("NFD").replace(COMBINING_MARKS, "");
  }
  return out;
}

/**
 * The normalised name key: unaccent, lowercase, then keep only [a-z0-9].
 *
 * Mirrors public.normalise_name_key(text) character for character.
 *
 * Note that this is empty for a name written entirely in a script unaccent()
 * can't romanise — "МОЛЧАТ ДОМА" has an empty name_search in the database too.
 * Callers filtering on the key must treat an empty result as "no usable
 * search term" rather than passing it to a LIKE, or the wildcard matches
 * every row.
 *
 * @param {unknown} value
 * @returns {string}
 */
export function normalisedNameKey(value) {
  return unaccent(value).toLowerCase().replace(/[^a-z0-9]/g, "");
}
