-- Migration: remove anonymous INSERT access to artists
--
-- Run once in the Supabase SQL editor. Safe to re-run (DROP POLICY IF
-- EXISTS and REVOKE are idempotent, and the whole thing is one
-- transaction).
--
-- Why:
--
--   A 2026-07 security review flagged that the RLS policy "Anyone can
--   submit a pending artist" (INSERT, roles {public}, WITH CHECK
--   directory_status = 'pending') combined with a table-level INSERT
--   grant to anon/authenticated let anyone holding the publishable key
--   (i.e. anyone, it ships in the browser bundle) POST rows directly to
--   /rest/v1/artists — bypassing every protection in /api/submit:
--   Turnstile, the honeypot, email verification, and the duplicate
--   check. The grant was table-level, so every column was writable
--   (notes, contact_info, booking_info, submitted_by_email, ...), not
--   just the ones the submission form uses.
--
--   Nothing uses this path. All app writes to artists go through the
--   service role, which bypasses RLS and grants entirely:
--     - /api/submit and /api/search-miss use getSupabaseAdminClient()
--     - admin and edit server actions use getSupabaseAdminClient()
--     - the browser-side anon client (src/lib/supabase/browser.ts) is
--       only used for auth on the login and reset-password pages
--
--   Fix: drop the policy and revoke the grant. Either alone would stop
--   the writes (RLS with no INSERT policy denies, and no grant denies
--   before RLS is even consulted); doing both keeps the policy list and
--   the ACL each telling the truth on their own.
--
--   TRUNCATE, REFERENCES, TRIGGER, and MAINTAIN are revoked too. They
--   are residue of Supabase's permissive defaults for new tables — not
--   reachable through PostgREST, but the public API roles have no
--   business holding them.
--
-- What is deliberately kept:
--
--   - The SELECT policy "Public can view approved artists" and the
--     column-level SELECT grants from
--     supabase_migration_artists_private_columns.sql. That pair is what
--     serves public directory reads: the column grants control WHICH
--     COLUMNS, the policy controls WHICH ROWS. This migration touches
--     neither.
--   - service_role keeps full access (admin panel, /api/submit,
--     enrichment scripts).
--
-- Caveats to keep in mind after this runs:
--
--   1. Anonymous submissions still work — they never used this path.
--      They go through POST /api/submit, which validates and writes
--      with the service role.
--
--   2. Default privileges in schema public are set per CREATING ROLE,
--      and only one of the two entries is permissive (corrected
--      2026-07-31 — an earlier version of this note claimed both were):
--
--        created by postgres       anon/authenticated get Dxtm only, so
--                                  a new table is NOT reachable through
--                                  PostgREST. This is the role the SQL
--                                  editor and CLI use, i.e. every table
--                                  we create.
--        created by supabase_admin anon/authenticated get ALL. Only
--                                  reachable via platform actions such
--                                  as installing an extension into
--                                  public, and not fixable from here:
--                                  ALTER DEFAULT PRIVILEGES FOR ROLE
--                                  supabase_admin needs membership in
--                                  that role, which postgres does not
--                                  have.
--
--      See supabase_check_public_role_exposure.sql, which monitors both
--      entries and the resulting grants.
--
-- Verification: with the publishable key, an insert must now be denied
-- (HTTP 401/403, SQLSTATE 42501 permission denied):
--
--   curl -s -X POST "$NEXT_PUBLIC_SUPABASE_URL/rest/v1/artists" \
--     -H "apikey: $NEXT_PUBLIC_SUPABASE_ANON_KEY" \
--     -H "Authorization: Bearer $NEXT_PUBLIC_SUPABASE_ANON_KEY" \
--     -H "Content-Type: application/json" \
--     -d '{"name":"grant probe","directory_status":"pending"}'
--
-- and a normal submission through the /submit form must still succeed.

BEGIN;

DROP POLICY IF EXISTS "Anyone can submit a pending artist" ON "public"."artists";

REVOKE INSERT, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
  ON TABLE "public"."artists" FROM "anon", "authenticated";

COMMIT;
