-- ============================================================
-- Schema dump via the Supabase SQL Editor (no CLI / Docker needed).
--
-- Paste this whole file into SQL Editor → New query → Run.
-- It returns ONE row with ONE column containing the complete DDL
-- for the `public` schema: enums, functions, tables (with
-- defaults, identity, not-null), constraints, indexes, views,
-- triggers, RLS enablement, and policies.
--
-- Copy that single cell into supabase_schema_current.sql.
--
-- Notes / limits vs. a real pg_dump:
--   * Covers the `public` schema only (not auth/storage internals,
--     which Supabase manages for you anyway).
--   * Storage buckets are not included — note them manually if the
--     schema file should document them (e.g. `artist-images`).
--   * Standalone sequences (rare in Supabase projects; identity
--     columns are handled) are not emitted.
-- ============================================================

with ddl as (

  -- 1 ── Enum types ───────────────────────────────────────────
  select 1 as ord, t.typname as name,
    'create type public.' || quote_ident(t.typname) || ' as enum ('
      || string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder)
      || ');' as stmt
  from pg_type t
  join pg_enum e on e.enumtypid = t.oid
  join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = 'public'
  group by t.typname

  union all

  -- 2 ── Functions ────────────────────────────────────────────
  select 2, p.proname,
    pg_get_functiondef(p.oid) || ';'
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind = 'f'

  union all

  -- 3 ── Tables (columns, defaults, identity, not null) ───────
  select 3, c.relname,
    'create table public.' || quote_ident(c.relname) || ' (' || chr(10)
      || string_agg(
           '  ' || quote_ident(a.attname) || ' '
           || format_type(a.atttypid, a.atttypmod)
           || case when a.attidentity = 'a' then ' generated always as identity'
                   when a.attidentity = 'd' then ' generated by default as identity'
                   else '' end
           || case when ad.adbin is not null
                   then ' default ' || pg_get_expr(ad.adbin, ad.adrelid)
                   else '' end
           || case when a.attnotnull then ' not null' else '' end,
           ',' || chr(10) order by a.attnum)
      || chr(10) || ');'
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef ad on ad.adrelid = c.oid and ad.adnum = a.attnum
  where n.nspname = 'public' and c.relkind = 'r'
  group by c.relname

  union all

  -- 4 ── Primary key / unique / check constraints ─────────────
  select 4, rel.relname || '.' || con.conname,
    'alter table public.' || quote_ident(rel.relname)
      || ' add constraint ' || quote_ident(con.conname) || ' '
      || pg_get_constraintdef(con.oid) || ';'
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  join pg_namespace n on n.oid = rel.relnamespace
  where n.nspname = 'public' and con.contype in ('p', 'u', 'c')

  union all

  -- 5 ── Foreign keys (after all tables + PKs exist) ──────────
  select 5, rel.relname || '.' || con.conname,
    'alter table public.' || quote_ident(rel.relname)
      || ' add constraint ' || quote_ident(con.conname) || ' '
      || pg_get_constraintdef(con.oid) || ';'
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  join pg_namespace n on n.oid = rel.relnamespace
  where n.nspname = 'public' and con.contype = 'f'

  union all

  -- 6 ── Indexes not already created by constraints ───────────
  select 6, i.indexname,
    i.indexdef || ';'
  from pg_indexes i
  where i.schemaname = 'public'
    and i.indexname not in (select conname from pg_constraint)

  union all

  -- 7 ── Views ────────────────────────────────────────────────
  select 7, c.relname,
    'create or replace view public.' || quote_ident(c.relname)
      || ' as' || chr(10) || pg_get_viewdef(c.oid, true)
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'v'

  union all

  -- 8 ── Triggers ─────────────────────────────────────────────
  select 8, t.tgname,
    pg_get_triggerdef(t.oid) || ';'
  from pg_trigger t
  join pg_class c on c.oid = t.tgrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and not t.tgisinternal

  union all

  -- 9 ── Enable row level security ────────────────────────────
  select 9, c.relname,
    'alter table public.' || quote_ident(c.relname)
      || ' enable row level security;'
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity

  union all

  -- 10 ── RLS policies ────────────────────────────────────────
  select 10, c.relname || '.' || p.polname,
    'create policy ' || quote_ident(p.polname)
      || ' on public.' || quote_ident(c.relname)
      || case when not p.polpermissive then ' as restrictive' else '' end
      || ' for ' || case p.polcmd
                      when 'r' then 'select'
                      when 'a' then 'insert'
                      when 'w' then 'update'
                      when 'd' then 'delete'
                      else 'all'
                    end
      || ' to ' || case
                     when p.polroles = '{0}'::oid[] then 'public'
                     else coalesce(
                       (select string_agg(quote_ident(r.rolname), ', ')
                        from pg_roles r where r.oid = any (p.polroles)),
                       'public')
                   end
      || coalesce(' using (' || pg_get_expr(p.polqual, p.polrelid) || ')', '')
      || coalesce(' with check (' || pg_get_expr(p.polwithcheck, p.polrelid) || ')', '')
      || ';'
  from pg_policy p
  join pg_class c on c.oid = p.polrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
)

select
  '-- Schema dump of the public schema, generated '
  || to_char(now(), 'YYYY-MM-DD') || chr(10)
  || '-- via supabase_dump_schema_via_sql_editor.sql'
  || chr(10) || chr(10)
  || string_agg(stmt, chr(10) || chr(10) order by ord, name) as schema_sql
from ddl;
