-- Migration: genre_tag_rules — the genre normalisation vocabulary.
-- Run once in the Supabase SQL editor, then seed with
--   node scripts/seed-genre-tag-rules.mjs
--
-- Why:
--
--   The raw-tag → canonical-genre transformations (GENRE_ALIASES,
--   BROAD_TAGS, WORD_FIXES) used to be hard-coded in
--   scripts/integrate-harvested-genres.mjs. This table replaces those
--   constants so the vocabulary can be edited without a code change —
--   via the admin panel (/admin/settings) or SQL. Scripts load the
--   whole table at startup through loadGenreVocab() in
--   scripts/lib/genre-vocab.mjs and REFUSE TO RUN if the table is
--   missing or empty (an empty vocabulary would silently create
--   duplicate genres).
--
-- One row per rule; `kind` says how the rule is applied:
--
--   'alias'    — raw_tag (lowercase) maps to the `canonical` display
--                name, e.g. 'dnb' → 'drum & bass'. The canonical value
--                sets the casing users see (e.g. 'EBM', 'UK garage').
--   'discard'  — raw_tag is too vague or not a genre ('seen live',
--                'electronic'); harvested rows matching it are marked
--                skipped and never promoted. `canonical` must be NULL.
--   'word_fix' — word-boundary substitution applied to the raw tag
--                BEFORE alias lookup, for concatenated forms that can
--                appear inside compound names: raw_tag is the word,
--                `canonical` its replacement ('avantgarde' →
--                'avant-garde', fixing 'avantgarde rock' too). The word
--                is matched literally (regex-escaped), never as a raw
--                pattern.
--
-- Precedence when the same raw_tag appears under several kinds
-- (deliberate for e.g. 'club music', which is discarded today but has
-- an alias → 'club' ready if it is ever un-discarded):
-- word fixes run first, then discard beats alias. This mirrors the old
-- hard-coded lookup order, so behaviour is unchanged after seeding.
--
-- Internal config, same posture as hoer_sync_state / resolved_artists:
-- RLS on, no anon/authenticated policy; only the service_role key
-- (scripts, admin server actions) can read or write.
--
-- Safe to re-run (idempotent).

CREATE TABLE IF NOT EXISTS "public"."genre_tag_rules" (
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "kind"       "text" NOT NULL,
    "raw_tag"    "text" NOT NULL,
    "canonical"  "text",
    "note"       "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "genre_tag_rules_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "genre_tag_rules_kind_check"
        CHECK ("kind" IN ('alias', 'discard', 'word_fix')),
    -- raw_tag is stored lowercase + trimmed; enforce so lookups
    -- (which lowercase the incoming tag) can never miss a rule.
    CONSTRAINT "genre_tag_rules_raw_tag_lowercase"
        CHECK ("raw_tag" = "lower"("btrim"("raw_tag")) AND "raw_tag" <> ''),
    -- discard rules carry no canonical; alias/word_fix must have one.
    CONSTRAINT "genre_tag_rules_canonical_shape"
        CHECK (("kind" = 'discard') = ("canonical" IS NULL)),
    CONSTRAINT "genre_tag_rules_kind_raw_tag_unique" UNIQUE ("kind", "raw_tag")
);

ALTER TABLE "public"."genre_tag_rules" OWNER TO "postgres";

ALTER TABLE "public"."genre_tag_rules" ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE "public"."genre_tag_rules" TO "service_role";
